Cell_City/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.home, name ='home'),
    path('accounts/profile/', views.home, name ='home'),
    path('products/<int:brand_id>/', views.products, name='products'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('increase_quantity/<int:cart_item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease_quantity/<int:cart_item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment-mode/<int:order_id>/', views.payment_mode, name='payment_mode'),
    path('order-confirmation/<str:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('invoice/<str:order_id>/', views.view_invoice, name='invoice'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search_results, name='search_results'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('edit_address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('delete_address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('feedback/', views.feedback, name='feedback'),
    path('thank-you/', views.thank_you, name='thank_you'),
    
]

rose/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Cell_City.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Cell_City/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify


# Create your models here.

class Brand(models.Model):
    name = models.CharField(max_length=100)
    image_url = models.URLField()

    def __str__(self):
        return self.name


class Product(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    stock_quantity = models.PositiveIntegerField(default=0)
    image_url = models.URLField()
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='specifications')
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}: {self.value}'
    
    def decrease_stock_quantity(self, quantity):
        if self.stock_quantity >= quantity:
            self.stock_quantity -= quantity
            self.save()
            return True
        return False


class CartItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.user.username


class Wishlist(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ManyToManyField('Product')

    def __str__(self):
        return f"Wishlist for {self.user.username}"

class Address(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=255)
    address_line_2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=10)
    mobile_number = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.address_line_1}, {self.city}, {self.state}, {self.country}"


from .utils import generate_order_id
from django.utils import timezone



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateTimeField(default=timezone.now)
    order_id = models.CharField(max_length=20, unique=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    is_cancelled = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.order_id:
            self.order_id = generate_order_id()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Order #{self.order_id} - {self.user.username}"

    def cancel_order(self):
        if not self.is_cancelled:
            self.is_cancelled = True
            self.save()
            order_items = OrderItem.objects.filter(order=self)
            for order_item in order_items:
                order_item.product.stock_quantity += order_item.quantity
                order_item.product.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def str(self):
        return self.name

Cell_City/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Address, Feedback
from django.contrib.auth.forms import User as AuthUser
from django.contrib.auth.models import User

class AddressForm(forms.ModelForm):
    mobile_regex = r'^\+?1?\d{9,15}$'
    mobile_number = forms.RegexField(regex=mobile_regex, max_length=15)

    class Meta:
        model = Address
        fields = ['address_line_1', 'address_line_2', 'city', 'state', 'country', 'zip_code', 'mobile_number']

class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', 'message']

Cell_City/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash, logout
from django.contrib import messages
from .models import Brand, Product, CartItem, Wishlist, Order, Address, OrderItem
from .forms import SignUpForm, FeedbackForm, AddressForm
from fuzzywuzzy import fuzz
from django.db.models import Q


def home(request):
    mobile_brands = Brand.objects.all() 
    context = {
        'mobile_brands': mobile_brands
    }
    return render(request, 'home.html', context)


def products(request, brand_id):
    brand = Brand.objects.get(id=brand_id)
    products = Product.objects.filter(brand=brand)
    context = {
        'products': products,
        'brand': brand,
    }
    return render(request, 'products.html', context)


def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    context = {
        'product': product
    }
    return render(request, 'product_detail.html', context)


def increase_quantity(request, cart_item_id):
    cart_item = CartItem.objects.get(pk=cart_item_id)
    if cart_item.quantity < cart_item.product.stock_quantity:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart')


def decrease_quantity(request, cart_item_id):
    cart_item = CartItem.objects.get(pk=cart_item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    elif cart_item.quantity <= 1:
        cart_item.delete()
    return redirect('cart')


@login_required(login_url='/login/')
def add_to_cart(request, product_id):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=product_id)
        cart_item, created = CartItem.objects.get_or_create(user=request.user, product=product)
    return redirect('cart')


@login_required(login_url='/login/')
def cart(request):
    cart_items = CartItem.objects.all()
    total_cost = 0
    for item in cart_items:
        item.subtotal = item.product.price * item.quantity
        total_cost += item.subtotal

    context = {
        'cart_items': cart_items,
        'total_cost': total_cost
    }
    return render(request, 'cart.html', context)


@login_required(login_url='/login/')
def wishlist(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        wishlist, created = Wishlist.objects.get_or_create(user=request.user)
        wishlist.products.add(product_id)
        return redirect('wishlist')
    else:
        wishlist = Wishlist.objects.filter(user=request.user).first()
        context = {'wishlist': wishlist}
        return render(request, 'wishlist.html', context)


@login_required(login_url='/login/')
def add_to_wishlist(request, product_id):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=product_id)
        wishlist, created = Wishlist.objects.get_or_create(user=request.user)
        wishlist.products.add(product)
        wishlist.save()
        return redirect('wishlist')
    else:
        return HttpResponse("Please login to add items to your wishlist.")


def remove_from_wishlist(request, product_id):
    if request.user.is_authenticated:
        product = Product.objects.get(pk=product_id)
        wishlist = Wishlist.objects.get(user=request.user)
        wishlist.products.remove(product)
    return redirect('wishlist')

@login_required(login_url='/login/')
def profile(request):
    saved = False
    max_addresses_reached = False
    user = request.user

    if request.method == 'POST':
        address_form = AddressForm(request.POST)

        if address_form.is_valid():
            if Address.objects.filter(customer=user).count() < 3:
                address = address_form.save(commit=False)
                address.customer = user
                address.save()
                saved = True
            else:
                max_addresses_reached = True
    else:
        address_form = AddressForm()

    addresses = Address.objects.filter(customer=user)

    return render(request, 'profile.html', {
        'user': user,
        'address_form': address_form,
        'saved': saved,
        'addresses': addresses,
        'max_addresses_reached': max_addresses_reached
    })


def checkout(request):
    user = request.user
    cart_items = CartItem.objects.filter(user=user)
    total_cost = 0
    for item in cart_items:
        total_cost += item.product.price * item.quantity

    if request.method == 'POST':
        selected_address_id = request.POST.get('selected_address')
        if selected_address_id:
            address = get_object_or_404(Address, id=selected_address_id)
        else:
            form = AddressForm(request.POST)
            if form.is_valid():
                address = form.save(commit=False)
                address.customer = user
                address.save()
            else:
                address = None

        if address:
            order = Order.objects.create(user=user, address=address, price=total_cost, total_cost=total_cost)

            for cart_item in cart_items:
                OrderItem.objects.create(order=order, product=cart_item.product, quantity=cart_item.quantity)
                cart_item.product.stock_quantity -= cart_item.quantity
                cart_item.product.save()

            cart_items.delete()
            return redirect('payment_mode', order_id=order.id)
    else:
        form = AddressForm()

    addresses = Address.objects.filter(customer=user)

    return render(request, 'checkout.html', {'form': form, 'cart_items': cart_items, 'total_cost': total_cost, 'addresses': addresses})



def payment_mode(request, order_id):
    order = Order.objects.get(id=order_id)

    if request.method == 'POST':
        selected_payment_mode = request.POST.get('payment_mode')
        return redirect('order_confirmation', order_id=order.id)

    return render(request, 'payment_mode.html')


def order_confirmation(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'order_confirmation.html', {'order': order})


def view_invoice(request, order_id):
    order = get_object_or_404(Order, order_id=order_id)
    return render(request, 'invoice.html', {'order': order})


def contact(request):
    return render(request, 'contact.html')


def search_results(request):
    query = request.GET.get('query')
    results = None

    if query:
        fuzzy_results = Product.objects.filter(
            Q(name__icontains=query) |
            Q(name__icontains=query.replace(' ', '')) |
            Q(name__icontains=query.lower())
        )

        similarity_scores = [
            (result, fuzz.token_set_ratio(query.lower(), result.name.lower()))
            for result in fuzzy_results
        ]

        sorted_results = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

        results = [result for result, _ in sorted_results]

    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'search_results.html', context)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


@login_required(login_url='/login/')
def my_orders(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        order = get_object_or_404(Order, id=order_id)
        if order.user == request.user and not order.is_cancelled:
            order.is_cancelled = True
            order.save()
            
            order_items = OrderItem.objects.filter(order=order)
            for order_item in order_items:
                product = order_item.product
                product.stock_quantity += order_item.quantity
                product.save()
                
            messages.success(request, 'Order cancelled successfully.')

    orders = Order.objects.filter(user=request.user)
    return render(request, 'my_orders.html', {'orders': orders})


def edit_address(request, address_id):
    address = Address.objects.get(id=address_id)
    if request.method == 'POST':
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = AddressForm(instance=address)

    return render(request, 'edit_address.html', {'form': form, 'address': address})


def delete_address(request, address_id):
    address = Address.objects.get(id=address_id)
    address.delete()
    return redirect('profile')


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('profile')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'change_password.html', {'form': form})


from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string

Cell_City/templates/add_address.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Addresses</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 20px;
        }
        h1, h2 {
            margin-bottom: 20px;
            color: #333;
        }
        .address-card {
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
        }
        .address-card p {
            margin: 5px 0;
        }
        .empty-addresses {
            color: #777;
        }
        .form-container {
            max-width: 500px;
            margin-top: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 20px;
            background-color: #f9f9f9;
        }
        button {
            display: inline-block;
            padding: 10px 15px;
            background-color: #333;
            color: #fff;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #555;
        }
    </style>
</head>
<body>
    <h1>Addresses</h1>
    {% if addresses %}
        {% for address in addresses %}
            <div class="address-card">
                <p><strong>Street:</strong> {{ address.street }}</p>
                <p><strong>City:</strong> {{ address.city }}</p>
                <p><strong>State:</strong> {{ address.state }}</p>
                <p><strong>Country:</strong> {{ address.country }}</p>
                <p><strong>Zip Code:</strong> {{ address.zip_code }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p class="empty-addresses">No addresses found.</p>
    {% endif %}
    
    <div class="form-container">
        <h2>Add New Address</h2>
        <form method="POST" action="{% url 'add_address' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Address</button>
        </form>
    </div>
</body>
</html>

Cell_City/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-image: url(https://img.freepik.com/free-vector/realistic-3d-advert-with-device_79603-1254.jpg);
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: inherit;
            margin-top: 150px;
            color: #fff;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            margin-top: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        input,
        textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            resize: vertical;
        }

        button {
            background-color: #4CAF50;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .contact-info {
            text-align: center;
            margin-top: 30px;
        }
        #home {
            color: rgb(0, 0, 0);
            background: rgb(97, 183, 220);
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            margin-left: 130px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Contact Us</h1>
        <form method="POST" id="contact-form">
            {% csrf_token %}
            <div>
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required>
            </div>
            <div>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div>
                <label for="message">Message:</label>
                <textarea id="message" name="message" required></textarea>
            </div>
            <button type="submit">Submit</button>
        </form>
        <div class="contact-info">
            <p>Email: Cell.city@mobile.in</p>
            <p>Mobile Number: +41 41007800</p>
        </div>
        <a id ='home' href="{% url 'home' %}">Return to Home</a>
    </div>
</body>
</html>

Cell_City/templates/edit_address.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Address</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        form label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        form input[type="text"],
        form input[type="number"],
        form select {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }
        form button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }
        form button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Edit Address</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>
</html>

Cell_City/templates/invoice.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color:rgb(205, 161, 145);
            
            
            
        }
        
        .invoice {
            width: 800px;
            margin: 0 auto;
            padding: 40px;
            font-family: 'Times New Roman', Times, serif;
            background-color:aliceblue;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            
            margin-top:28px;
        }
        
        .invoice-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }
        
        .invoice-header h1 {
            margin: 0;
            font-size: 28px;
        }
        
        .invoice-header p {
            margin: 0;
            font-size: 18px;
        }
        
        .order-details {
            margin-bottom: 20px;
        }
        
        .order-details p {
            margin: 0;
            font-size: 16px;
            line-height: 1.4;
        }
        
        .invoice-footer {
            margin-top: 40px;
            text-align: center;
        }
        
        .invoice-footer a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            font-size: 16px;
            border-radius: 4px;
        }
        
        .invoice-footer a:hover {
            background-color: #0056b3;
        }

        #invoice{
            background-color: rgb(37, 203, 87);
                }
    </style>
</head>
<body>
    <div class="invoice">
        <div class="invoice-header">
            <h1>Invoice</h1>
            <p>Order ID: {{ order.order_id }}</p>
        </div>
    
        <div class="order-details">
            <p>Name: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Contact: {{ order.address.mobile_number }}</p>
            <p>Order Date: {{ order.order_date }}</p>
            <div class="address-card">
                <h3>Delivery Address</h3>
                <p>Address Line 1: {{ order.address.address_line_1 }}</p>
                <p>Address Line 2: {{ order.address.address_line_2 }}</p>
                <p>City: {{ order.address.city }}</p>
                <p>State: {{ order.address.state }}</p>
                <p>Postal Code: {{ order.address.zip_code }}</p>
            </div>
        </div>
        
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for order_item in order.orderitem_set.all %}
                    <tr>
                        <td>{{ order_item.product.name }}</td>
                        <td>{{ order_item.product.price }}</td>
                        <td>{{ order_item.quantity }}</td>
                        <td>{{ order_item.subtotal }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <p>Total Cost: {{ order.total_cost }}</p>
    
        
        <a href="{% url 'invoice' order.order_id %}" class="btn btn-primary" id="invoice" download>Download Invoice</a>

        <div class="invoice-footer">
            <a href="{% url 'home' %}" class="btn btn-secondary">Return to Homepage</a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Cell_City/templates/my_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Orders</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
            background-image: url("https://helios-i.mashable.com/imagery/articles/06Go9Vbhq1du0dJoo1bbZQ6/images-297.fill.size_2000x1125.v1629162609.jpg");
            background-size: cover;
        }
       
h1 {
  margin-bottom: 20px;
  font-size: 24px;
}


#home {
  display: inline-block;
  margin-bottom: 20px;
  padding: 10px 20px;
  background-color: #f0f0f0;
  color: #333;
  text-decoration: none;
  border: none;
  border-radius: 5px;
  font-size: 16px;
}

.order {
  margin-bottom: 20px;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
}


.order h3 {
  margin-top: 0;
  font-size: 20px;
}


.order p {
  margin-bottom: 10px;
  font-size: 16px;
}


form {
  display: inline-block;
  margin-right: 10px;
}

button[type="submit"] {
  padding: 5px 10px;
  background-color: #dc3545;
  color: #fff;
  border: none;
  border-radius: 5px;
  font-size: 14px;
  cursor: pointer;
}


a {
  display: inline-block;
  margin-top: 10px;
  font-size: 16px;
  text-decoration: none;
  color: #007bff;
}


.cancelled {
  font-size: 16px;
  color: #dc3545;
  font-weight: bold;
}


.no-orders {
  font-size: 16px;
  font-style: italic;
  color: #888;
}

</style>


</head>
<body>
  <h1>My Orders</h1>
  <a href="{% url 'home' %}" class="btn btn-secondary" id="home">Return to Home</a>

  {% if orders %}
    {% for order in orders reversed %}
    <div class="order">
        <h3>Order ID: {{ order.order_id }}</h3>
        <p>Order Date: {{ order.order_date }}</p>
        {% for order_item in order.orderitem_set.all %}
        <p>Product Name: {{ order_item.product.name }}</p>
        {% endfor %}
        <p>Total: {{ order.total_cost }}</p>
        {% if not order.is_cancelled %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ order.id }}">
                <button type="submit" class="btn btn-danger">Cancel Order</button>
            </form>
            <a href="{% url 'invoice' order.order_id %}">View Invoice</a>
        {% else %}
            <p class="cancelled">Order Cancelled</p>
        {% endif %}
    </div>
    {% endfor %}
{% else %}
    <p class="no-orders">No orders found.</p>
{% endif %}

</body>
</html>